### ISSUE TITLE
Wrong ELFCLASS

### ISSUE THREAD

**Issue by CanadianJeff** [patrickjennings/D2-Maphack-for-Linux#2]
```
jefferyw@xubuntu:/tmp$ export LD_PRELOAD="/usr/local/lib/snoogans.so"
jefferyw@xubuntu:/tmp$ wine ~/.wine/drive_c/Program\ Files\ \(x86\)/Diablo\ II/Diablo\ II.exe -w --skiptobnet --nofixedaspect


*** INIT MODULE ***

populating kernel32 functions... err: could not find location of kernel32.dll

*** FAILED TO LOAD MODULE ***

exiting...


*** INIT MODULE ***

populating kernel32 functions... err: could not find location of kernel32.dll

*** FAILED TO LOAD MODULE ***

exiting...
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/usr/local/lib/snoogans.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.


*** INIT MODULE ***

populating kernel32 functions... err: could not find location of kernel32.dll

*** FAILED TO LOAD MODULE ***

exiting...
```

**Comment by patrickjennings** [comment]
snoogans wasn't setup to work from preload but it's certainly something I can look into adding. Have you tried using the d2-inject script to inject snoogans into the running process?

**Comment by CanadianJeff** [comment]
when I used the inject script the game froze it might be because I am trying this is a 64bit wine container when I get home I will attempt creating a 32bit wine container

**Comment by CanadianJeff** [comment]
ok just tried with a 32bit wine container it says it loaded but when I press tab game crashes

**Comment by patrickjennings** [comment]
I figured I would give an update on this issue as it has been two weeks.

I think I can recreate the issue you are having. You can uncomment out the #define DEBUG line in snoogans.0.5/debug.h and recompile to see where it is freezing. I press tab and the game crashes at the D2COMMON_add_room_data call in snoogans/maphack.c line 254 after the "add room data..." output. I believe that the pointers for D2Common are being modified as previous calls into the Diablo 2 DLLs are executed successfully.

I haven't figured out yet what is modifying the addresses. I used PlayOnLinux to run a bunch of different versions of Wine and found that it froze in the same spot all the way back to Wine version 1.5.23. Before this version of wine, LOD would not run for me.

I was able to get this maphack working 5 months ago and it is a shame that it is not working now. I will continue to investigate this issue and why the address offsets are changing. I did an objdump of the Game.exe file and am trying to track down the appropriate functions but it could take me awhile...

For now, your best bet is to create a Windows VM and use [slashdiablo-maphack](https://github.com/blurt/slashdiablo-maphack) as snoogans seems to be the only native maphack for Linux. Sorry for the wait and the bad news.
